### ISSUE TITLE
Space problem

### ISSUE THREAD

**Issue by BBavouzet** [awsmug/dev-bash-wp-docker#1]
Hello, and thanks for wp-devops :)

I found problem with space in name of folder name :
`vendor/bin/devops.sh: ligne 3 : cd: trop d'arguments` (in english : too many arguments)
With a path without space, script run.
My system : Xubuntu 18.04 LTS

**Comment by mahype** [comment]
Hi,

I will check that on my testing system! Thank you for reporting!

Greetings,

Sven

**Comment by mahype** [comment]
Does this happen on the command `vendor/bin/devops.sh init`?

**Comment by mahype** [comment]
@BBavouzet I have installed Xubunto on my VMWare but I could not reproduce the error. Can you please tell me, which command you have used and also the parameters you have used.

**Comment by BBavouzet** [comment]
Hi,
I've run `vendor/bin/devops.sh init` into my documents folder inside another folder named DevOps Wordpress. Like this :
`~/Documents/DevOps Wordpress/$ vendor/bin/devops.sh init`

**Comment by mahype** [comment]
OK. I will check that and will try to reproduce it.

**Comment by mahype** [comment]
I have fixed it. If you use the dev-master version it should also work with white spaces now. Can you confirm that?

**Comment by BBavouzet** [comment]
Hi,
I've tested with spaces, it works !! Good work !
And thank you,
See you

**Comment by mahype** [comment]
👍
