### ISSUE TITLE
Docker-compose version

### ISSUE THREAD

**Issue by BBavouzet** [awsmug/dev-bash-wp-docker#2]
Hello,

I had to change the version to 3.3 for docker compose run on my linux system (Xubuntu 18.04 LTS).

Thanks

**Comment by mahype** [comment]
Hi,

an at which point can I help you or what can I change?

Greetings,

Sven

**Comment by BBavouzet** [comment]
Hi,

Add option in script to choose version to all docker-compose files.
Or, maybe, if it's possible, detect the max version of the docker-compose installed supports ?

Greetings,

Benoît

**Comment by mahype** [comment]
OK. I will think about how to manage that. Thank you fot that hint!

**Comment by mahype** [comment]
For now I have downgraded the version to 3.2 by default. Because of downwards compatibility of docker-compose.yml this should be OK.

**Comment by BBavouzet** [comment]
Hi,
It's ok for me, it work without version modification ;)
See you
