### ISSUE TITLE
Uppercase in folder project

### ISSUE THREAD

**Issue by BBavouzet** [awsmug/dev-bash-wp-docker#3]
Hi,

I've found another problem with uppercase in my folder project name : `~/Documents/DevOps Wordpress/`.
Because container docker name default are less uppercase and, I think, the script consider the folder's name.

Greetings,

Benoît

**Comment by mahype** [comment]
Ahh OK! Thats a good point! I will check an fixt that.

**Comment by mahype** [comment]
I have made a commit to fix the uppercase problem in dev-master. If you use awsmug/wp-devops:dev-master this problem should be fixed.

**Comment by BBavouzet** [comment]
Hi,
Sorry for delays...
I've tried, it works now with upper-cases !
thank you,
See you

**Comment by mahype** [comment]
Perfect! 👍
