### ISSUE TITLE
Phpmyadmin container

### ISSUE THREAD

**Issue by BBavouzet** [awsmug/dev-bash-wp-docker#4]
Hi,

I've small issue with the phpmyadmin container.
It restarts on PC boot and cause errors on run `./devops.sh up`. I run `docker stop $(docker ps -aq)` for resolve it.
I think it's because of `restart: always` in docker-compose-site line 48 and line 51 in docker-compose-plugin and docker-compose-them.

See you

**Comment by mahype** [comment]
Hi! I will check that. I had also this problem.

**Comment by mahype** [comment]
I have changed it in the template files. It should be fixed now in dev-master and will come in 0.2.0.

After a "./devops.sh init all", the docker-compose.yml file would be overwritten.

Thank you for the hint! 👍
